language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run deploy

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  target_branch: gh_pages # default target branch gh_pages
  on:
    branch: master
